GET http://localhost:5086/

###

GET http://localhost:5086/games

###

GET http://localhost:5086/games/2

###

POST http://localhost:5086/games
Content-Type: application/json

{    
    "Name": "Minecraft", 
    "Genre": "Infancy Simulator", 
    "Price": 19.99,
    "ReleaseDate": "2011-11-18"
}

###

PUT http://localhost:5086/games/2
Content-Type: application/json

{
    "name": "Final Fantasy XIX",
    "genre": "Role Playing Game",
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

###

DELETE http://localhost:5086/games/2