GET http://localhost:5086/

###

GET http://localhost:5086/games

###

GET http://localhost:5086/games/6

###

POST http://localhost:5086/games
Content-Type: application/json

{    
    "Name": "Street Fighter II", 
    "GenreId": 2, 
    "Price": 19.99,
    "ReleaseDate": "1992-07-15"
}

# private static readonly List<GameSumaryDto> games = [
#     new (
#         1,
#         "Street Fighter II",
#         "Fighting",
#         19.99M,
#         new DateOnly(1992, 7, 15)
#     ),
#     new (
#         2,
#         "Final Fantasy XIX",
#         "RPG",
#         59.99M,
#         new DateOnly(2010, 9, 30)
#     ),
#     new (
#         3,
#         "FIFA 23",
#         "Sports",
#         69.99M,
#         new DateOnly(2022, 9, 27)
#     ),
# ];


###

PUT http://localhost:5086/games/2
Content-Type: application/json

{
    # "name": "Final Fantasy XIX",
    "genre": "Role Playing Game",
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

###

DELETE http://localhost:5086/games/6